### ISSUE TITLE
Filtering turns on for 2h only

### ISSUE THREAD

**Issue by TRIROG** [mathieu-mp/intex-spa#31]
Hey!

as i discovered that original intex app scheduling was somewhat flaky (sometimes it worked other times not) i decided to implement scheduling of filter running thrugh my local HA.
However i have noticed that sending ON command for filtering turns it on for 2 hours and it shuts off automatically after that (the display shows 02h when sending filter on command). 

in contrast turning filtering on the control panel offers 2,4 or 6h running time. 

Is it possible that there is also different remote command for running time and could be implemented?

thx

**Comment by mathieu-mp** [comment]
Hi @TRIROG 

This issue is a duplicate for #16.

I am sorry, but we cannot change this behavior, as it reproduces the official Intex app action.
It could be different commands for runtime filtering, but we don't know of any.

I will close this issue, but don't hesitate to reopen it if you identify such a command.

Regards, Mathieu.
